name: athlete_surveyor
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  gsheets: ^0.5.0
  provider: ^6.1.2
  uuid: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
   - lib/resources/images/download-7.jpg
